### ISSUE TITLE
GitHub Username

### ISSUE THREAD

**Issue by ajartille** [no-longer-open/furry-tribble#1]
### `ajar`

Could I please have your GitHub username? It is the name of my nonprofit human rights organization and we have some big developments in progress (https://ajar.org — https://github.com/ajar-fdn). `ajar-fdn` does not sound as good as `ajar`, of course. Please let me know if there is any way. Thank you! 

— `A`aron `J`. `Ar`tille (`AJAr`)

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/changing-your-github-username

**Comment by ajar** [comment]
Yes @ajartille that would be fine. I'm not really using this account anyway. I can change username when you are ready to take it.

**Comment by ajartille** [comment]
Thank you so much! I'd be ready. You really are just about the best...

**Comment by no-longer-open** [comment]
@ajartille go for it!

**Comment by AJAr** [comment]
You really are too kind. Thank you again! I hope you have a great day today :)

**Comment by no-longer-open** [comment]
you too my friend! Good luck with the non-profit!
